import { ColorSchemeScript, AppShell } from '@mantine/core';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import '@web/lib/fontawesome';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <link
          rel="shortcut icon"
          href="/favicon.ico"
        />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body className={inter.className}>
        <Providers>
          {/* When adding Mantine components, such as the AppShell, remember to put them in the render.utils.tsx file */}
          <AppShell header={{ height: 60 }}>{children}</AppShell>
        </Providers>
      </body>
    </html>
  );
}
