/* tslint:disable */
/* eslint-disable */
/**
 * Nest basic API for users
 * The users API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginUserDto
 */
export interface LoginUserDto {
    /**
     * 
     * @type {string}
     * @memberof LoginUserDto
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof LoginUserDto
     */
    password: string;
}

/**
 * Check if a given object implements the LoginUserDto interface.
 */
export function instanceOfLoginUserDto(value: object): value is LoginUserDto {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginUserDtoFromJSON(json: any): LoginUserDto {
    return LoginUserDtoFromJSONTyped(json, false);
}

export function LoginUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginUserDto {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function LoginUserDtoToJSON(value?: LoginUserDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

